export const MOTIVATION_QUOTES: string[] = [
  "Your competition is practicing. Just saying.",
  "Your dream job isn't going to DM you.",
  "One more mock. Future you says thanks.",
  "Confidence.exe is loading.",
  "Rejection is just unpaid feedback.",
  "Don't panic. You have prepared for this.",
  "Your resume can't answer for you.",
  "Practice now, flex later.",
  "Be nervous. Do it anyway.",
  "Your comfort zone has no placement drives.",
  "Skill up before luck shows up.",
  "Main character energy, placement edition.",
  "Less scrolling, more scoring.",
  "Your future salary is watching.",
  "That interview won't crack itself.",
  "Ctrl+C won't work in interviews.",
  "Google can't sit beside you.",
  "AI can help. You still have to speak.",
  'Don\'t let "Tell me about yourself" defeat you.',
  "Your first answer doesn't have to be perfect.",
  "Awkward today, confident tomorrow.",
  "Mistakes are basically free coaching.",
  "Your competition has entered the chat.",
  "Plot twist: you actually get better.",
  "Don't ghost your preparation.",
  "LinkedIn won't save you. Skills might.",
  "Your degree got you here. Skills take you further.",
  "No pressure, just your career.",
  "Your dream company has no idea you exist. Yet.",
  "Prepare like your Wi-Fi depends on it.",
  'One day, "I\'m preparing" becomes "I\'m placed."',
  "Your excuses have excellent attendance.",
  "Placement season doesn't care about vibes.",
  'Less "I\'ll do it tomorrow", more "Done today."',
  "Your future self is judging your consistency.",
  "Be the candidate recruiters remember.",
  "Don't just attend. Improve.",
  "Another mock? Yes. Another excuse? No.",
  "Your confidence needs training too.",
  "Nervousness is just confidence buffering.",
  "Don't fear the interview. Fear being unprepared.",
  "Your keyboard skills won't answer HR questions.",
  "Talk less to yourself, practice more with us.",
  "Your dream CTC needs some effort.",
  "If preparation was easy, everyone would be placed.",
  "Your competition is probably online right now.",
  "Stop refreshing LinkedIn. Start improving.",
  "Rejection hurts less when you're improving.",
  "You can't fake preparation for long.",
  "Your weak area just got exposed. Good.",
  "Congratulations, you found something to improve.",
  "Today's awkward answer is tomorrow's smooth answer.",
  "Be bad at it until you're good at it.",
  "Nobody starts interview-ready.",
  "Your first mock might hurt. That's the point.",
  "Don't aim to sound perfect. Aim to sound prepared.",
  "Confidence without preparation is just premium-level overconfidence.",
  "Preparation: cheaper than regret.",
  "Your interview isn't a viva. Breathe.",
  "You've survived college. You can survive a mock.",
  'No company wants "I\'ll try." Show them "I can."',
  "Don't wait for confidence. Build it.",
  "Your career deserves more than last-minute preparation.",
  "Talent is great. Preparation makes it useful.",
  "Your potential called. It wants consistency.",
  "Don't compete for attention. Compete with yesterday's you.",
  "Your leaderboard position isn't permanent. Neither is your weakness.",
  "Someone is improving while you're thinking about improving.",
  "You don't need motivation every day. You need a habit.",
  "Procrastination has entered the meeting. Decline it.",
  "Your phone knows you better than your recruiter should.",
  "Your screen time is impressive. Your preparation can be too.",
  '"I\'ll start tomorrow" has terrible placement statistics.',
  "Don't let your laziness become your career strategy.",
  "Your future CTC is allergic to excuses.",
  "Placement season: 1, excuses: 0.",
  'Keep practicing. Your recruiter won\'t accept "I was nervous."',
  "The goal isn't to know everything. It's to keep learning.",
  "Smart people practice too.",
  "You can panic after you prepare.",
  "Your mock interview is judging you less than your recruiter will.",
  "Think of mocks as rehearsals, not punishments.",
  "Get uncomfortable now. Get confident later.",
  "Your dream offer needs more than good vibes.",
  "If you can scroll for an hour, you can practice for ten minutes.",
  "One skill at a time. One step closer.",
  "Don't wait for the perfect moment. There isn't one.",
  "Your competition isn't your enemy. Your inconsistency is.",
  "Today's effort is tomorrow's advantage.",
  "Be the student who came prepared.",
  "Your future interview starts with today's practice.",
  "Nobody remembers your excuses. Recruiters remember your answers.",
  "Keep going. Even your bad attempts are data.",
  "You came here to improve. Might as well.",
  'Practice until "Tell me about yourself" stops being scary.',
  "Less overthinking, more attempting.",
  "Your placement story is still being written.",
  "Make your next attempt better than your last.",
  "Your dream role deserves a prepared version of you.",
  "Don't just hope for an offer. Prepare for one.",
  "Loading confidence... please keep practicing.",
  "Almost ready is still not ready.",
  "Your moment will come. Be ready when it does.",
  "Practice today. Screenshot the offer tomorrow.",
];

export const INTERVIEW_MOTIVATION_QUOTES: string[] = [
  "Your mock interview is the dress rehearsal your placement deserves.",
  "Every interview answered is another layer of armour.",
  "The panel isn't there to break you. They're there to test you.",
  "One more question practised today is one less surprise tomorrow.",
  "Speak slowly. Think clearly. Finish strong.",
  "Preparation turns nervous energy into performance.",
  "The interview you fear most is the one that prepares you best.",
  "Your answers today build the offers of tomorrow.",
  "Stumble now, so you soar in the real room.",
  "An interview is a conversation, not a confession.",
  "Breathe in. Answer. Breathe out. Repeat.",
  "You're not competing with the panel. You're showing them you're ready.",
  "Every mock is a deposit in your confidence account.",
  "The right answer is practised, not improvised.",
  "Walk in prepared, and the room gets easier.",
  "Your first answer sets the tone. Make it yours.",
  "Interviews reward the prepared, not the perfect.",
  "Nerves are proof you care. Use that.",
  "The best time to prepare was yesterday. The second best is now.",
  "Say it out loud — silence is where answers die.",
  "Your resume gets you in. Your presence keeps you there.",
  "Don't just know your project. Be able to defend it.",
  "Clarity beats cleverness in every interview.",
  "The STAR method is your story's best friend.",
  "Speak in examples, not adjectives.",
  "An offer is earned in the minutes before the interview begins.",
  "Pause before you answer. Control is confident.",
  "Mock now, so the real panel can't rattle you.",
  "Your preparation is a quiet superpower nobody sees coming.",
  "Every weak answer today becomes a strong one tomorrow.",
  "The panel wants to hire someone. Let them see that's you.",
  "Confidence is what remains after preparation.",
  "Interview day is just the final rehearsal you practised for.",
  "Difficult questions are where prepared candidates win.",
  "Your voice is the strongest thing you present. Use it.",
  "Practise the answer until it becomes your truth.",
  "Arrive early, prepare more, worry less.",
  "An interview is a two-way door. You're choosing them too.",
  "The candidate who prepares for the 'why' owns the room.",
  "Small daily practice, big placement payoff.",
  "Your calm is your competitive advantage.",
  "Rehearse aloud. Your brain speaks better out loud.",
  "The offer letter is written in your preparation notes.",
  "Don't memorise answers. Master the thinking underneath them.",
  "Every question is a chance to show the panel you can think.",
  "Your preparation is the plot. Your interview is the reveal.",
  "Strong answers come from calm, practised minds.",
  "The panel is rooting for your best answer. Give it.",
  "Future you is watching this mock. Make them proud.",
  "One prepared sentence beats ten nervous ones.",
];

export function randomMotivationQuote(): string {
  const index = Math.floor(Math.random() * MOTIVATION_QUOTES.length);
  return MOTIVATION_QUOTES[index] ?? "Loading…";
}

export function sampleMotivationQuotes(
  count: number,
  pool: readonly string[] = MOTIVATION_QUOTES,
): string[] {
  const src = [...pool];
  const result: string[] = [];
  while (result.length < count && src.length > 0) {
    const index = Math.floor(Math.random() * src.length);
    const picked = src[index];
    if (picked !== undefined) {
      result.push(picked);
      src.splice(index, 1);
    }
  }
  return result;
}
