/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidateRouteRouteImport } from './routes/candidate/route'
import { Route as DowntimeRouteImport } from './routes/downtime'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as TacRouteImport } from './routes/tac'
import { Route as CandidateAplrTrainingRouteImport } from './routes/candidate/aplr-training'
import { Route as CandidateAuthRouteImport } from './routes/candidate/auth'
import { Route as CandidateBasicMathTrainingRouteImport } from './routes/candidate/basic-math-training'
import { Route as CandidateChatRouteImport } from './routes/candidate/chat'
import { Route as CandidateCommunicationTrainingRouteImport } from './routes/candidate/communication-training'
import { Route as CandidateCommunicationTrainingHistoryRouteImport } from './routes/candidate/communication-training-history'
import { Route as CandidateCommunicationTrainingTipsRouteImport } from './routes/candidate/communication-training-tips'
import { Route as CandidateCoursesRouteImport } from './routes/candidate/courses'
import { Route as CandidateDailyTargetsRouteImport } from './routes/candidate/daily-targets'
import { Route as CandidateDiscussionForumRouteImport } from './routes/candidate/discussion-forum'
import { Route as CandidateDsaTrainingRouteImport } from './routes/candidate/dsa-training'
import { Route as CandidateEnglishTrainingRouteImport } from './routes/candidate/english-training'
import { Route as CandidateEnglishTrainingHistoryRouteImport } from './routes/candidate/english-training-history'
import { Route as CandidateEnglishTrainingTipsRouteImport } from './routes/candidate/english-training-tips'
import { Route as CandidateGdHistoryRouteImport } from './routes/candidate/gd-history'
import { Route as CandidateGdRoomRouteImport } from './routes/candidate/gd-room'
import { Route as CandidateGdTrainingRouteImport } from './routes/candidate/gd-training'
import { Route as CandidateLeaderboardRouteImport } from './routes/candidate/leaderboard'
import { Route as CandidateLearningRouteImport } from './routes/candidate/learning'
import { Route as CandidateMockInterviewRouteImport } from './routes/candidate/mock-interview'
import { Route as CandidateMockInterviewHistoryRouteImport } from './routes/candidate/mock-interview-history'
import { Route as CandidateNotificationsRouteImport } from './routes/candidate/notifications'
import { Route as CandidateOnboardingRouteImport } from './routes/candidate/onboarding'
import { Route as CandidateProfileRouteImport } from './routes/candidate/profile'
import { Route as CandidateResumeBuilderRouteImport } from './routes/candidate/resume-builder'
import { Route as CandidateRoadmapDrillRouteImport } from './routes/candidate/roadmap-drill'
import { Route as CandidateSelfTrainingRouteImport } from './routes/candidate/self-training'
import { Route as CandidateSituationalTrainingRouteImport } from './routes/candidate/situational-training'
import { Route as CandidateStudentMessageRouteImport } from './routes/candidate/student-message'
import { Route as CandidateTechnicalTrainingRouteImport } from './routes/candidate/technical-training'
import { Route as CandidateTutorialsRouteImport } from './routes/candidate/tutorials'
import { Route as ClientAuthRouteImport } from './routes/client/auth'
import { Route as ClientChatRouteImport } from './routes/client/chat'
import { Route as ClientClientChatRouteImport } from './routes/client/client-chat'
import { Route as ClientClientOnboardingRouteImport } from './routes/client/client-onboarding'
import { Route as ClientClientProfileRouteImport } from './routes/client/client-profile'
import { Route as ClientCompaniesRouteImport } from './routes/client/companies'
import { Route as ClientCompanyDrivesRouteImport } from './routes/client/company-drives'
import { Route as ClientDrivesRouteImport } from './routes/client/drives'
import { Route as ClientInstituteBillingRouteImport } from './routes/client/institute-billing'
import { Route as ClientInstitutionAuthRouteImport } from './routes/client/institution-auth'
import { Route as ClientLaunchTargetsRouteImport } from './routes/client/launch-targets'
import { Route as ClientLdTrainingRouteImport } from './routes/client/ld-training'
import { Route as ClientNotificationsRouteImport } from './routes/client/notifications'
import { Route as ClientOnboardingRouteImport } from './routes/client/onboarding'
import { Route as ClientPlacementCellRouteImport } from './routes/client/placement-cell'
import { Route as ClientProfileRouteImport } from './routes/client/profile'
import { Route as ClientReportsRouteImport } from './routes/client/reports'
import { Route as ClientStudentsRouteImport } from './routes/client/students'
import { Route as CommunicationTrainingReportSessionIdRouteImport } from './routes/communication-training-report.$sessionId'
import { Route as CompanyDrivesCompanyIdRouteImport } from './routes/company-drives_.$companyId'
import { Route as EnglishTrainingReportSessionIdRouteImport } from './routes/english-training-report.$sessionId'
import { Route as GdReportGdIdRouteImport } from './routes/gd-report.$gdId'
import { Route as InterviewAnalysisInterviewIdRouteImport } from './routes/interview-analysis.$interviewId'
import { Route as MockInterviewTranscriptInterviewIdRouteImport } from './routes/mock-interview-transcript.$interviewId'
import { Route as StudentActivityStudentIdRouteImport } from './routes/student-activity.$studentId'
import { Route as StudentDataStudentIdRouteImport } from './routes/student-data.$studentId'
import { Route as StudentDetailStudentIdRouteImport } from './routes/student-detail.$studentId'
import { Route as StudentInterviewEvidenceStudentIdInterviewIdRouteImport } from './routes/student-interview-evidence.$studentId.$interviewId'
import { Route as StudentModuleStudentIdModuleKeyRouteImport } from './routes/student-module.$studentId.$moduleKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRouteRoute = CandidateRouteRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const DowntimeRoute = DowntimeRouteImport.update({
  id: '/downtime',
  path: '/downtime',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const TacRoute = TacRouteImport.update({
  id: '/tac',
  path: '/tac',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateAplrTrainingRoute = CandidateAplrTrainingRouteImport.update({
  id: '/aplr-training',
  path: '/aplr-training',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateAuthRoute = CandidateAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateBasicMathTrainingRoute =
  CandidateBasicMathTrainingRouteImport.update({
    id: '/basic-math-training',
    path: '/basic-math-training',
    getParentRoute: () => CandidateRouteRoute,
  } as any)
const CandidateChatRoute = CandidateChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateCommunicationTrainingRoute =
  CandidateCommunicationTrainingRouteImport.update({
    id: '/communication-training',
    path: '/communication-training',
    getParentRoute: () => CandidateRouteRoute,
  } as any)
const CandidateCommunicationTrainingHistoryRoute =
  CandidateCommunicationTrainingHistoryRouteImport.update({
    id: '/communication-training-history',
    path: '/communication-training-history',
    getParentRoute: () => CandidateRouteRoute,
  } as any)
const CandidateCommunicationTrainingTipsRoute =
  CandidateCommunicationTrainingTipsRouteImport.update({
    id: '/communication-training-tips',
    path: '/communication-training-tips',
    getParentRoute: () => CandidateRouteRoute,
  } as any)
const CandidateCoursesRoute = CandidateCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateDailyTargetsRoute = CandidateDailyTargetsRouteImport.update({
  id: '/daily-targets',
  path: '/daily-targets',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateDiscussionForumRoute =
  CandidateDiscussionForumRouteImport.update({
    id: '/discussion-forum',
    path: '/discussion-forum',
    getParentRoute: () => CandidateRouteRoute,
  } as any)
const CandidateDsaTrainingRoute = CandidateDsaTrainingRouteImport.update({
  id: '/dsa-training',
  path: '/dsa-training',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateEnglishTrainingRoute =
  CandidateEnglishTrainingRouteImport.update({
    id: '/english-training',
    path: '/english-training',
    getParentRoute: () => CandidateRouteRoute,
  } as any)
const CandidateEnglishTrainingHistoryRoute =
  CandidateEnglishTrainingHistoryRouteImport.update({
    id: '/english-training-history',
    path: '/english-training-history',
    getParentRoute: () => CandidateRouteRoute,
  } as any)
const CandidateEnglishTrainingTipsRoute =
  CandidateEnglishTrainingTipsRouteImport.update({
    id: '/english-training-tips',
    path: '/english-training-tips',
    getParentRoute: () => CandidateRouteRoute,
  } as any)
const CandidateGdHistoryRoute = CandidateGdHistoryRouteImport.update({
  id: '/gd-history',
  path: '/gd-history',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateGdRoomRoute = CandidateGdRoomRouteImport.update({
  id: '/gd-room',
  path: '/gd-room',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateGdTrainingRoute = CandidateGdTrainingRouteImport.update({
  id: '/gd-training',
  path: '/gd-training',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateLeaderboardRoute = CandidateLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateLearningRoute = CandidateLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateMockInterviewRoute = CandidateMockInterviewRouteImport.update({
  id: '/mock-interview',
  path: '/mock-interview',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateMockInterviewHistoryRoute =
  CandidateMockInterviewHistoryRouteImport.update({
    id: '/mock-interview-history',
    path: '/mock-interview-history',
    getParentRoute: () => CandidateRouteRoute,
  } as any)
const CandidateNotificationsRoute = CandidateNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateOnboardingRoute = CandidateOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateResumeBuilderRoute = CandidateResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateRoadmapDrillRoute = CandidateRoadmapDrillRouteImport.update({
  id: '/roadmap-drill',
  path: '/roadmap-drill',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateSelfTrainingRoute = CandidateSelfTrainingRouteImport.update({
  id: '/self-training',
  path: '/self-training',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateSituationalTrainingRoute =
  CandidateSituationalTrainingRouteImport.update({
    id: '/situational-training',
    path: '/situational-training',
    getParentRoute: () => CandidateRouteRoute,
  } as any)
const CandidateStudentMessageRoute = CandidateStudentMessageRouteImport.update({
  id: '/student-message',
  path: '/student-message',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const CandidateTechnicalTrainingRoute =
  CandidateTechnicalTrainingRouteImport.update({
    id: '/technical-training',
    path: '/technical-training',
    getParentRoute: () => CandidateRouteRoute,
  } as any)
const CandidateTutorialsRoute = CandidateTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => CandidateRouteRoute,
} as any)
const ClientAuthRoute = ClientAuthRouteImport.update({
  id: '/client/auth',
  path: '/client/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientChatRoute = ClientChatRouteImport.update({
  id: '/client/chat',
  path: '/client/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientClientChatRoute = ClientClientChatRouteImport.update({
  id: '/client/client-chat',
  path: '/client/client-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientClientOnboardingRoute = ClientClientOnboardingRouteImport.update({
  id: '/client/client-onboarding',
  path: '/client/client-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientClientProfileRoute = ClientClientProfileRouteImport.update({
  id: '/client/client-profile',
  path: '/client/client-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientCompaniesRoute = ClientCompaniesRouteImport.update({
  id: '/client/companies',
  path: '/client/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientCompanyDrivesRoute = ClientCompanyDrivesRouteImport.update({
  id: '/client/company-drives',
  path: '/client/company-drives',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDrivesRoute = ClientDrivesRouteImport.update({
  id: '/client/drives',
  path: '/client/drives',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientInstituteBillingRoute = ClientInstituteBillingRouteImport.update({
  id: '/client/institute-billing',
  path: '/client/institute-billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientInstitutionAuthRoute = ClientInstitutionAuthRouteImport.update({
  id: '/client/institution-auth',
  path: '/client/institution-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLaunchTargetsRoute = ClientLaunchTargetsRouteImport.update({
  id: '/client/launch-targets',
  path: '/client/launch-targets',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLdTrainingRoute = ClientLdTrainingRouteImport.update({
  id: '/client/ld-training',
  path: '/client/ld-training',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientNotificationsRoute = ClientNotificationsRouteImport.update({
  id: '/client/notifications',
  path: '/client/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientOnboardingRoute = ClientOnboardingRouteImport.update({
  id: '/client/onboarding',
  path: '/client/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPlacementCellRoute = ClientPlacementCellRouteImport.update({
  id: '/client/placement-cell',
  path: '/client/placement-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/client/profile',
  path: '/client/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientReportsRoute = ClientReportsRouteImport.update({
  id: '/client/reports',
  path: '/client/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientStudentsRoute = ClientStudentsRouteImport.update({
  id: '/client/students',
  path: '/client/students',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationTrainingReportSessionIdRoute =
  CommunicationTrainingReportSessionIdRouteImport.update({
    id: '/communication-training-report/$sessionId',
    path: '/communication-training-report/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanyDrivesCompanyIdRoute = CompanyDrivesCompanyIdRouteImport.update({
  id: '/company-drives_/$companyId',
  path: '/company-drives/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishTrainingReportSessionIdRoute =
  EnglishTrainingReportSessionIdRouteImport.update({
    id: '/english-training-report/$sessionId',
    path: '/english-training-report/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GdReportGdIdRoute = GdReportGdIdRouteImport.update({
  id: '/gd-report/$gdId',
  path: '/gd-report/$gdId',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewAnalysisInterviewIdRoute =
  InterviewAnalysisInterviewIdRouteImport.update({
    id: '/interview-analysis/$interviewId',
    path: '/interview-analysis/$interviewId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MockInterviewTranscriptInterviewIdRoute =
  MockInterviewTranscriptInterviewIdRouteImport.update({
    id: '/mock-interview-transcript/$interviewId',
    path: '/mock-interview-transcript/$interviewId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentActivityStudentIdRoute =
  StudentActivityStudentIdRouteImport.update({
    id: '/student-activity/$studentId',
    path: '/student-activity/$studentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentDataStudentIdRoute = StudentDataStudentIdRouteImport.update({
  id: '/student-data/$studentId',
  path: '/student-data/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDetailStudentIdRoute = StudentDetailStudentIdRouteImport.update({
  id: '/student-detail/$studentId',
  path: '/student-detail/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentInterviewEvidenceStudentIdInterviewIdRoute =
  StudentInterviewEvidenceStudentIdInterviewIdRouteImport.update({
    id: '/student-interview-evidence/$studentId/$interviewId',
    path: '/student-interview-evidence/$studentId/$interviewId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentModuleStudentIdModuleKeyRoute =
  StudentModuleStudentIdModuleKeyRouteImport.update({
    id: '/student-module/$studentId/$moduleKey',
    path: '/student-module/$studentId/$moduleKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidate': typeof CandidateRouteRouteWithChildren
  '/downtime': typeof DowntimeRoute
  '/get-started': typeof GetStartedRoute
  '/logout': typeof LogoutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sandbox': typeof SandboxRoute
  '/tac': typeof TacRoute
  '/candidate/aplr-training': typeof CandidateAplrTrainingRoute
  '/candidate/auth': typeof CandidateAuthRoute
  '/candidate/basic-math-training': typeof CandidateBasicMathTrainingRoute
  '/candidate/chat': typeof CandidateChatRoute
  '/candidate/communication-training': typeof CandidateCommunicationTrainingRoute
  '/candidate/communication-training-history': typeof CandidateCommunicationTrainingHistoryRoute
  '/candidate/communication-training-tips': typeof CandidateCommunicationTrainingTipsRoute
  '/candidate/courses': typeof CandidateCoursesRoute
  '/candidate/daily-targets': typeof CandidateDailyTargetsRoute
  '/candidate/discussion-forum': typeof CandidateDiscussionForumRoute
  '/candidate/dsa-training': typeof CandidateDsaTrainingRoute
  '/candidate/english-training': typeof CandidateEnglishTrainingRoute
  '/candidate/english-training-history': typeof CandidateEnglishTrainingHistoryRoute
  '/candidate/english-training-tips': typeof CandidateEnglishTrainingTipsRoute
  '/candidate/gd-history': typeof CandidateGdHistoryRoute
  '/candidate/gd-room': typeof CandidateGdRoomRoute
  '/candidate/gd-training': typeof CandidateGdTrainingRoute
  '/candidate/leaderboard': typeof CandidateLeaderboardRoute
  '/candidate/learning': typeof CandidateLearningRoute
  '/candidate/mock-interview': typeof CandidateMockInterviewRoute
  '/candidate/mock-interview-history': typeof CandidateMockInterviewHistoryRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/onboarding': typeof CandidateOnboardingRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/resume-builder': typeof CandidateResumeBuilderRoute
  '/candidate/roadmap-drill': typeof CandidateRoadmapDrillRoute
  '/candidate/self-training': typeof CandidateSelfTrainingRoute
  '/candidate/situational-training': typeof CandidateSituationalTrainingRoute
  '/candidate/student-message': typeof CandidateStudentMessageRoute
  '/candidate/technical-training': typeof CandidateTechnicalTrainingRoute
  '/candidate/tutorials': typeof CandidateTutorialsRoute
  '/client/auth': typeof ClientAuthRoute
  '/client/chat': typeof ClientChatRoute
  '/client/client-chat': typeof ClientClientChatRoute
  '/client/client-onboarding': typeof ClientClientOnboardingRoute
  '/client/client-profile': typeof ClientClientProfileRoute
  '/client/companies': typeof ClientCompaniesRoute
  '/client/company-drives': typeof ClientCompanyDrivesRoute
  '/client/drives': typeof ClientDrivesRoute
  '/client/institute-billing': typeof ClientInstituteBillingRoute
  '/client/institution-auth': typeof ClientInstitutionAuthRoute
  '/client/launch-targets': typeof ClientLaunchTargetsRoute
  '/client/ld-training': typeof ClientLdTrainingRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/onboarding': typeof ClientOnboardingRoute
  '/client/placement-cell': typeof ClientPlacementCellRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/reports': typeof ClientReportsRoute
  '/client/students': typeof ClientStudentsRoute
  '/communication-training-report/$sessionId': typeof CommunicationTrainingReportSessionIdRoute
  '/company-drives/$companyId': typeof CompanyDrivesCompanyIdRoute
  '/english-training-report/$sessionId': typeof EnglishTrainingReportSessionIdRoute
  '/gd-report/$gdId': typeof GdReportGdIdRoute
  '/interview-analysis/$interviewId': typeof InterviewAnalysisInterviewIdRoute
  '/mock-interview-transcript/$interviewId': typeof MockInterviewTranscriptInterviewIdRoute
  '/student-activity/$studentId': typeof StudentActivityStudentIdRoute
  '/student-data/$studentId': typeof StudentDataStudentIdRoute
  '/student-detail/$studentId': typeof StudentDetailStudentIdRoute
  '/student-interview-evidence/$studentId/$interviewId': typeof StudentInterviewEvidenceStudentIdInterviewIdRoute
  '/student-module/$studentId/$moduleKey': typeof StudentModuleStudentIdModuleKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidate': typeof CandidateRouteRouteWithChildren
  '/downtime': typeof DowntimeRoute
  '/get-started': typeof GetStartedRoute
  '/logout': typeof LogoutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sandbox': typeof SandboxRoute
  '/tac': typeof TacRoute
  '/candidate/aplr-training': typeof CandidateAplrTrainingRoute
  '/candidate/auth': typeof CandidateAuthRoute
  '/candidate/basic-math-training': typeof CandidateBasicMathTrainingRoute
  '/candidate/chat': typeof CandidateChatRoute
  '/candidate/communication-training': typeof CandidateCommunicationTrainingRoute
  '/candidate/communication-training-history': typeof CandidateCommunicationTrainingHistoryRoute
  '/candidate/communication-training-tips': typeof CandidateCommunicationTrainingTipsRoute
  '/candidate/courses': typeof CandidateCoursesRoute
  '/candidate/daily-targets': typeof CandidateDailyTargetsRoute
  '/candidate/discussion-forum': typeof CandidateDiscussionForumRoute
  '/candidate/dsa-training': typeof CandidateDsaTrainingRoute
  '/candidate/english-training': typeof CandidateEnglishTrainingRoute
  '/candidate/english-training-history': typeof CandidateEnglishTrainingHistoryRoute
  '/candidate/english-training-tips': typeof CandidateEnglishTrainingTipsRoute
  '/candidate/gd-history': typeof CandidateGdHistoryRoute
  '/candidate/gd-room': typeof CandidateGdRoomRoute
  '/candidate/gd-training': typeof CandidateGdTrainingRoute
  '/candidate/leaderboard': typeof CandidateLeaderboardRoute
  '/candidate/learning': typeof CandidateLearningRoute
  '/candidate/mock-interview': typeof CandidateMockInterviewRoute
  '/candidate/mock-interview-history': typeof CandidateMockInterviewHistoryRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/onboarding': typeof CandidateOnboardingRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/resume-builder': typeof CandidateResumeBuilderRoute
  '/candidate/roadmap-drill': typeof CandidateRoadmapDrillRoute
  '/candidate/self-training': typeof CandidateSelfTrainingRoute
  '/candidate/situational-training': typeof CandidateSituationalTrainingRoute
  '/candidate/student-message': typeof CandidateStudentMessageRoute
  '/candidate/technical-training': typeof CandidateTechnicalTrainingRoute
  '/candidate/tutorials': typeof CandidateTutorialsRoute
  '/client/auth': typeof ClientAuthRoute
  '/client/chat': typeof ClientChatRoute
  '/client/client-chat': typeof ClientClientChatRoute
  '/client/client-onboarding': typeof ClientClientOnboardingRoute
  '/client/client-profile': typeof ClientClientProfileRoute
  '/client/companies': typeof ClientCompaniesRoute
  '/client/company-drives': typeof ClientCompanyDrivesRoute
  '/client/drives': typeof ClientDrivesRoute
  '/client/institute-billing': typeof ClientInstituteBillingRoute
  '/client/institution-auth': typeof ClientInstitutionAuthRoute
  '/client/launch-targets': typeof ClientLaunchTargetsRoute
  '/client/ld-training': typeof ClientLdTrainingRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/onboarding': typeof ClientOnboardingRoute
  '/client/placement-cell': typeof ClientPlacementCellRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/reports': typeof ClientReportsRoute
  '/client/students': typeof ClientStudentsRoute
  '/communication-training-report/$sessionId': typeof CommunicationTrainingReportSessionIdRoute
  '/company-drives/$companyId': typeof CompanyDrivesCompanyIdRoute
  '/english-training-report/$sessionId': typeof EnglishTrainingReportSessionIdRoute
  '/gd-report/$gdId': typeof GdReportGdIdRoute
  '/interview-analysis/$interviewId': typeof InterviewAnalysisInterviewIdRoute
  '/mock-interview-transcript/$interviewId': typeof MockInterviewTranscriptInterviewIdRoute
  '/student-activity/$studentId': typeof StudentActivityStudentIdRoute
  '/student-data/$studentId': typeof StudentDataStudentIdRoute
  '/student-detail/$studentId': typeof StudentDetailStudentIdRoute
  '/student-interview-evidence/$studentId/$interviewId': typeof StudentInterviewEvidenceStudentIdInterviewIdRoute
  '/student-module/$studentId/$moduleKey': typeof StudentModuleStudentIdModuleKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidate': typeof CandidateRouteRouteWithChildren
  '/downtime': typeof DowntimeRoute
  '/get-started': typeof GetStartedRoute
  '/logout': typeof LogoutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sandbox': typeof SandboxRoute
  '/tac': typeof TacRoute
  '/candidate/aplr-training': typeof CandidateAplrTrainingRoute
  '/candidate/auth': typeof CandidateAuthRoute
  '/candidate/basic-math-training': typeof CandidateBasicMathTrainingRoute
  '/candidate/chat': typeof CandidateChatRoute
  '/candidate/communication-training': typeof CandidateCommunicationTrainingRoute
  '/candidate/communication-training-history': typeof CandidateCommunicationTrainingHistoryRoute
  '/candidate/communication-training-tips': typeof CandidateCommunicationTrainingTipsRoute
  '/candidate/courses': typeof CandidateCoursesRoute
  '/candidate/daily-targets': typeof CandidateDailyTargetsRoute
  '/candidate/discussion-forum': typeof CandidateDiscussionForumRoute
  '/candidate/dsa-training': typeof CandidateDsaTrainingRoute
  '/candidate/english-training': typeof CandidateEnglishTrainingRoute
  '/candidate/english-training-history': typeof CandidateEnglishTrainingHistoryRoute
  '/candidate/english-training-tips': typeof CandidateEnglishTrainingTipsRoute
  '/candidate/gd-history': typeof CandidateGdHistoryRoute
  '/candidate/gd-room': typeof CandidateGdRoomRoute
  '/candidate/gd-training': typeof CandidateGdTrainingRoute
  '/candidate/leaderboard': typeof CandidateLeaderboardRoute
  '/candidate/learning': typeof CandidateLearningRoute
  '/candidate/mock-interview': typeof CandidateMockInterviewRoute
  '/candidate/mock-interview-history': typeof CandidateMockInterviewHistoryRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/onboarding': typeof CandidateOnboardingRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/resume-builder': typeof CandidateResumeBuilderRoute
  '/candidate/roadmap-drill': typeof CandidateRoadmapDrillRoute
  '/candidate/self-training': typeof CandidateSelfTrainingRoute
  '/candidate/situational-training': typeof CandidateSituationalTrainingRoute
  '/candidate/student-message': typeof CandidateStudentMessageRoute
  '/candidate/technical-training': typeof CandidateTechnicalTrainingRoute
  '/candidate/tutorials': typeof CandidateTutorialsRoute
  '/client/auth': typeof ClientAuthRoute
  '/client/chat': typeof ClientChatRoute
  '/client/client-chat': typeof ClientClientChatRoute
  '/client/client-onboarding': typeof ClientClientOnboardingRoute
  '/client/client-profile': typeof ClientClientProfileRoute
  '/client/companies': typeof ClientCompaniesRoute
  '/client/company-drives': typeof ClientCompanyDrivesRoute
  '/client/drives': typeof ClientDrivesRoute
  '/client/institute-billing': typeof ClientInstituteBillingRoute
  '/client/institution-auth': typeof ClientInstitutionAuthRoute
  '/client/launch-targets': typeof ClientLaunchTargetsRoute
  '/client/ld-training': typeof ClientLdTrainingRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/onboarding': typeof ClientOnboardingRoute
  '/client/placement-cell': typeof ClientPlacementCellRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/reports': typeof ClientReportsRoute
  '/client/students': typeof ClientStudentsRoute
  '/communication-training-report/$sessionId': typeof CommunicationTrainingReportSessionIdRoute
  '/company-drives_/$companyId': typeof CompanyDrivesCompanyIdRoute
  '/english-training-report/$sessionId': typeof EnglishTrainingReportSessionIdRoute
  '/gd-report/$gdId': typeof GdReportGdIdRoute
  '/interview-analysis/$interviewId': typeof InterviewAnalysisInterviewIdRoute
  '/mock-interview-transcript/$interviewId': typeof MockInterviewTranscriptInterviewIdRoute
  '/student-activity/$studentId': typeof StudentActivityStudentIdRoute
  '/student-data/$studentId': typeof StudentDataStudentIdRoute
  '/student-detail/$studentId': typeof StudentDetailStudentIdRoute
  '/student-interview-evidence/$studentId/$interviewId': typeof StudentInterviewEvidenceStudentIdInterviewIdRoute
  '/student-module/$studentId/$moduleKey': typeof StudentModuleStudentIdModuleKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidate'
    | '/downtime'
    | '/get-started'
    | '/logout'
    | '/privacy-policy'
    | '/sandbox'
    | '/tac'
    | '/candidate/aplr-training'
    | '/candidate/auth'
    | '/candidate/basic-math-training'
    | '/candidate/chat'
    | '/candidate/communication-training'
    | '/candidate/communication-training-history'
    | '/candidate/communication-training-tips'
    | '/candidate/courses'
    | '/candidate/daily-targets'
    | '/candidate/discussion-forum'
    | '/candidate/dsa-training'
    | '/candidate/english-training'
    | '/candidate/english-training-history'
    | '/candidate/english-training-tips'
    | '/candidate/gd-history'
    | '/candidate/gd-room'
    | '/candidate/gd-training'
    | '/candidate/leaderboard'
    | '/candidate/learning'
    | '/candidate/mock-interview'
    | '/candidate/mock-interview-history'
    | '/candidate/notifications'
    | '/candidate/onboarding'
    | '/candidate/profile'
    | '/candidate/resume-builder'
    | '/candidate/roadmap-drill'
    | '/candidate/self-training'
    | '/candidate/situational-training'
    | '/candidate/student-message'
    | '/candidate/technical-training'
    | '/candidate/tutorials'
    | '/client/auth'
    | '/client/chat'
    | '/client/client-chat'
    | '/client/client-onboarding'
    | '/client/client-profile'
    | '/client/companies'
    | '/client/company-drives'
    | '/client/drives'
    | '/client/institute-billing'
    | '/client/institution-auth'
    | '/client/launch-targets'
    | '/client/ld-training'
    | '/client/notifications'
    | '/client/onboarding'
    | '/client/placement-cell'
    | '/client/profile'
    | '/client/reports'
    | '/client/students'
    | '/communication-training-report/$sessionId'
    | '/company-drives/$companyId'
    | '/english-training-report/$sessionId'
    | '/gd-report/$gdId'
    | '/interview-analysis/$interviewId'
    | '/mock-interview-transcript/$interviewId'
    | '/student-activity/$studentId'
    | '/student-data/$studentId'
    | '/student-detail/$studentId'
    | '/student-interview-evidence/$studentId/$interviewId'
    | '/student-module/$studentId/$moduleKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidate'
    | '/downtime'
    | '/get-started'
    | '/logout'
    | '/privacy-policy'
    | '/sandbox'
    | '/tac'
    | '/candidate/aplr-training'
    | '/candidate/auth'
    | '/candidate/basic-math-training'
    | '/candidate/chat'
    | '/candidate/communication-training'
    | '/candidate/communication-training-history'
    | '/candidate/communication-training-tips'
    | '/candidate/courses'
    | '/candidate/daily-targets'
    | '/candidate/discussion-forum'
    | '/candidate/dsa-training'
    | '/candidate/english-training'
    | '/candidate/english-training-history'
    | '/candidate/english-training-tips'
    | '/candidate/gd-history'
    | '/candidate/gd-room'
    | '/candidate/gd-training'
    | '/candidate/leaderboard'
    | '/candidate/learning'
    | '/candidate/mock-interview'
    | '/candidate/mock-interview-history'
    | '/candidate/notifications'
    | '/candidate/onboarding'
    | '/candidate/profile'
    | '/candidate/resume-builder'
    | '/candidate/roadmap-drill'
    | '/candidate/self-training'
    | '/candidate/situational-training'
    | '/candidate/student-message'
    | '/candidate/technical-training'
    | '/candidate/tutorials'
    | '/client/auth'
    | '/client/chat'
    | '/client/client-chat'
    | '/client/client-onboarding'
    | '/client/client-profile'
    | '/client/companies'
    | '/client/company-drives'
    | '/client/drives'
    | '/client/institute-billing'
    | '/client/institution-auth'
    | '/client/launch-targets'
    | '/client/ld-training'
    | '/client/notifications'
    | '/client/onboarding'
    | '/client/placement-cell'
    | '/client/profile'
    | '/client/reports'
    | '/client/students'
    | '/communication-training-report/$sessionId'
    | '/company-drives/$companyId'
    | '/english-training-report/$sessionId'
    | '/gd-report/$gdId'
    | '/interview-analysis/$interviewId'
    | '/mock-interview-transcript/$interviewId'
    | '/student-activity/$studentId'
    | '/student-data/$studentId'
    | '/student-detail/$studentId'
    | '/student-interview-evidence/$studentId/$interviewId'
    | '/student-module/$studentId/$moduleKey'
  id:
    | '__root__'
    | '/'
    | '/candidate'
    | '/downtime'
    | '/get-started'
    | '/logout'
    | '/privacy-policy'
    | '/sandbox'
    | '/tac'
    | '/candidate/aplr-training'
    | '/candidate/auth'
    | '/candidate/basic-math-training'
    | '/candidate/chat'
    | '/candidate/communication-training'
    | '/candidate/communication-training-history'
    | '/candidate/communication-training-tips'
    | '/candidate/courses'
    | '/candidate/daily-targets'
    | '/candidate/discussion-forum'
    | '/candidate/dsa-training'
    | '/candidate/english-training'
    | '/candidate/english-training-history'
    | '/candidate/english-training-tips'
    | '/candidate/gd-history'
    | '/candidate/gd-room'
    | '/candidate/gd-training'
    | '/candidate/leaderboard'
    | '/candidate/learning'
    | '/candidate/mock-interview'
    | '/candidate/mock-interview-history'
    | '/candidate/notifications'
    | '/candidate/onboarding'
    | '/candidate/profile'
    | '/candidate/resume-builder'
    | '/candidate/roadmap-drill'
    | '/candidate/self-training'
    | '/candidate/situational-training'
    | '/candidate/student-message'
    | '/candidate/technical-training'
    | '/candidate/tutorials'
    | '/client/auth'
    | '/client/chat'
    | '/client/client-chat'
    | '/client/client-onboarding'
    | '/client/client-profile'
    | '/client/companies'
    | '/client/company-drives'
    | '/client/drives'
    | '/client/institute-billing'
    | '/client/institution-auth'
    | '/client/launch-targets'
    | '/client/ld-training'
    | '/client/notifications'
    | '/client/onboarding'
    | '/client/placement-cell'
    | '/client/profile'
    | '/client/reports'
    | '/client/students'
    | '/communication-training-report/$sessionId'
    | '/company-drives_/$companyId'
    | '/english-training-report/$sessionId'
    | '/gd-report/$gdId'
    | '/interview-analysis/$interviewId'
    | '/mock-interview-transcript/$interviewId'
    | '/student-activity/$studentId'
    | '/student-data/$studentId'
    | '/student-detail/$studentId'
    | '/student-interview-evidence/$studentId/$interviewId'
    | '/student-module/$studentId/$moduleKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidateRouteRoute: typeof CandidateRouteRouteWithChildren
  DowntimeRoute: typeof DowntimeRoute
  GetStartedRoute: typeof GetStartedRoute
  LogoutRoute: typeof LogoutRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SandboxRoute: typeof SandboxRoute
  TacRoute: typeof TacRoute
  ClientAuthRoute: typeof ClientAuthRoute
  ClientChatRoute: typeof ClientChatRoute
  ClientClientChatRoute: typeof ClientClientChatRoute
  ClientClientOnboardingRoute: typeof ClientClientOnboardingRoute
  ClientClientProfileRoute: typeof ClientClientProfileRoute
  ClientCompaniesRoute: typeof ClientCompaniesRoute
  ClientCompanyDrivesRoute: typeof ClientCompanyDrivesRoute
  ClientDrivesRoute: typeof ClientDrivesRoute
  ClientInstituteBillingRoute: typeof ClientInstituteBillingRoute
  ClientInstitutionAuthRoute: typeof ClientInstitutionAuthRoute
  ClientLaunchTargetsRoute: typeof ClientLaunchTargetsRoute
  ClientLdTrainingRoute: typeof ClientLdTrainingRoute
  ClientNotificationsRoute: typeof ClientNotificationsRoute
  ClientOnboardingRoute: typeof ClientOnboardingRoute
  ClientPlacementCellRoute: typeof ClientPlacementCellRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientReportsRoute: typeof ClientReportsRoute
  ClientStudentsRoute: typeof ClientStudentsRoute
  CommunicationTrainingReportSessionIdRoute: typeof CommunicationTrainingReportSessionIdRoute
  CompanyDrivesCompanyIdRoute: typeof CompanyDrivesCompanyIdRoute
  EnglishTrainingReportSessionIdRoute: typeof EnglishTrainingReportSessionIdRoute
  GdReportGdIdRoute: typeof GdReportGdIdRoute
  InterviewAnalysisInterviewIdRoute: typeof InterviewAnalysisInterviewIdRoute
  MockInterviewTranscriptInterviewIdRoute: typeof MockInterviewTranscriptInterviewIdRoute
  StudentActivityStudentIdRoute: typeof StudentActivityStudentIdRoute
  StudentDataStudentIdRoute: typeof StudentDataStudentIdRoute
  StudentDetailStudentIdRoute: typeof StudentDetailStudentIdRoute
  StudentInterviewEvidenceStudentIdInterviewIdRoute: typeof StudentInterviewEvidenceStudentIdInterviewIdRoute
  StudentModuleStudentIdModuleKeyRoute: typeof StudentModuleStudentIdModuleKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downtime': {
      id: '/downtime'
      path: '/downtime'
      fullPath: '/downtime'
      preLoaderRoute: typeof DowntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tac': {
      id: '/tac'
      path: '/tac'
      fullPath: '/tac'
      preLoaderRoute: typeof TacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/aplr-training': {
      id: '/candidate/aplr-training'
      path: '/aplr-training'
      fullPath: '/candidate/aplr-training'
      preLoaderRoute: typeof CandidateAplrTrainingRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/auth': {
      id: '/candidate/auth'
      path: '/auth'
      fullPath: '/candidate/auth'
      preLoaderRoute: typeof CandidateAuthRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/basic-math-training': {
      id: '/candidate/basic-math-training'
      path: '/basic-math-training'
      fullPath: '/candidate/basic-math-training'
      preLoaderRoute: typeof CandidateBasicMathTrainingRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/chat': {
      id: '/candidate/chat'
      path: '/chat'
      fullPath: '/candidate/chat'
      preLoaderRoute: typeof CandidateChatRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/communication-training': {
      id: '/candidate/communication-training'
      path: '/communication-training'
      fullPath: '/candidate/communication-training'
      preLoaderRoute: typeof CandidateCommunicationTrainingRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/communication-training-history': {
      id: '/candidate/communication-training-history'
      path: '/communication-training-history'
      fullPath: '/candidate/communication-training-history'
      preLoaderRoute: typeof CandidateCommunicationTrainingHistoryRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/communication-training-tips': {
      id: '/candidate/communication-training-tips'
      path: '/communication-training-tips'
      fullPath: '/candidate/communication-training-tips'
      preLoaderRoute: typeof CandidateCommunicationTrainingTipsRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/courses': {
      id: '/candidate/courses'
      path: '/courses'
      fullPath: '/candidate/courses'
      preLoaderRoute: typeof CandidateCoursesRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/daily-targets': {
      id: '/candidate/daily-targets'
      path: '/daily-targets'
      fullPath: '/candidate/daily-targets'
      preLoaderRoute: typeof CandidateDailyTargetsRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/discussion-forum': {
      id: '/candidate/discussion-forum'
      path: '/discussion-forum'
      fullPath: '/candidate/discussion-forum'
      preLoaderRoute: typeof CandidateDiscussionForumRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/dsa-training': {
      id: '/candidate/dsa-training'
      path: '/dsa-training'
      fullPath: '/candidate/dsa-training'
      preLoaderRoute: typeof CandidateDsaTrainingRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/english-training': {
      id: '/candidate/english-training'
      path: '/english-training'
      fullPath: '/candidate/english-training'
      preLoaderRoute: typeof CandidateEnglishTrainingRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/english-training-history': {
      id: '/candidate/english-training-history'
      path: '/english-training-history'
      fullPath: '/candidate/english-training-history'
      preLoaderRoute: typeof CandidateEnglishTrainingHistoryRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/english-training-tips': {
      id: '/candidate/english-training-tips'
      path: '/english-training-tips'
      fullPath: '/candidate/english-training-tips'
      preLoaderRoute: typeof CandidateEnglishTrainingTipsRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/gd-history': {
      id: '/candidate/gd-history'
      path: '/gd-history'
      fullPath: '/candidate/gd-history'
      preLoaderRoute: typeof CandidateGdHistoryRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/gd-room': {
      id: '/candidate/gd-room'
      path: '/gd-room'
      fullPath: '/candidate/gd-room'
      preLoaderRoute: typeof CandidateGdRoomRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/gd-training': {
      id: '/candidate/gd-training'
      path: '/gd-training'
      fullPath: '/candidate/gd-training'
      preLoaderRoute: typeof CandidateGdTrainingRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/leaderboard': {
      id: '/candidate/leaderboard'
      path: '/leaderboard'
      fullPath: '/candidate/leaderboard'
      preLoaderRoute: typeof CandidateLeaderboardRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/learning': {
      id: '/candidate/learning'
      path: '/learning'
      fullPath: '/candidate/learning'
      preLoaderRoute: typeof CandidateLearningRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/mock-interview': {
      id: '/candidate/mock-interview'
      path: '/mock-interview'
      fullPath: '/candidate/mock-interview'
      preLoaderRoute: typeof CandidateMockInterviewRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/mock-interview-history': {
      id: '/candidate/mock-interview-history'
      path: '/mock-interview-history'
      fullPath: '/candidate/mock-interview-history'
      preLoaderRoute: typeof CandidateMockInterviewHistoryRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/notifications': {
      id: '/candidate/notifications'
      path: '/notifications'
      fullPath: '/candidate/notifications'
      preLoaderRoute: typeof CandidateNotificationsRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/onboarding': {
      id: '/candidate/onboarding'
      path: '/onboarding'
      fullPath: '/candidate/onboarding'
      preLoaderRoute: typeof CandidateOnboardingRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/resume-builder': {
      id: '/candidate/resume-builder'
      path: '/resume-builder'
      fullPath: '/candidate/resume-builder'
      preLoaderRoute: typeof CandidateResumeBuilderRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/roadmap-drill': {
      id: '/candidate/roadmap-drill'
      path: '/roadmap-drill'
      fullPath: '/candidate/roadmap-drill'
      preLoaderRoute: typeof CandidateRoadmapDrillRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/self-training': {
      id: '/candidate/self-training'
      path: '/self-training'
      fullPath: '/candidate/self-training'
      preLoaderRoute: typeof CandidateSelfTrainingRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/situational-training': {
      id: '/candidate/situational-training'
      path: '/situational-training'
      fullPath: '/candidate/situational-training'
      preLoaderRoute: typeof CandidateSituationalTrainingRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/student-message': {
      id: '/candidate/student-message'
      path: '/student-message'
      fullPath: '/candidate/student-message'
      preLoaderRoute: typeof CandidateStudentMessageRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/technical-training': {
      id: '/candidate/technical-training'
      path: '/technical-training'
      fullPath: '/candidate/technical-training'
      preLoaderRoute: typeof CandidateTechnicalTrainingRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/candidate/tutorials': {
      id: '/candidate/tutorials'
      path: '/tutorials'
      fullPath: '/candidate/tutorials'
      preLoaderRoute: typeof CandidateTutorialsRouteImport
      parentRoute: typeof CandidateRouteRoute
    }
    '/client/auth': {
      id: '/client/auth'
      path: '/client/auth'
      fullPath: '/client/auth'
      preLoaderRoute: typeof ClientAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/chat': {
      id: '/client/chat'
      path: '/client/chat'
      fullPath: '/client/chat'
      preLoaderRoute: typeof ClientChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/client-chat': {
      id: '/client/client-chat'
      path: '/client/client-chat'
      fullPath: '/client/client-chat'
      preLoaderRoute: typeof ClientClientChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/client-onboarding': {
      id: '/client/client-onboarding'
      path: '/client/client-onboarding'
      fullPath: '/client/client-onboarding'
      preLoaderRoute: typeof ClientClientOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/client-profile': {
      id: '/client/client-profile'
      path: '/client/client-profile'
      fullPath: '/client/client-profile'
      preLoaderRoute: typeof ClientClientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/companies': {
      id: '/client/companies'
      path: '/client/companies'
      fullPath: '/client/companies'
      preLoaderRoute: typeof ClientCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/company-drives': {
      id: '/client/company-drives'
      path: '/client/company-drives'
      fullPath: '/client/company-drives'
      preLoaderRoute: typeof ClientCompanyDrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/drives': {
      id: '/client/drives'
      path: '/client/drives'
      fullPath: '/client/drives'
      preLoaderRoute: typeof ClientDrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/institute-billing': {
      id: '/client/institute-billing'
      path: '/client/institute-billing'
      fullPath: '/client/institute-billing'
      preLoaderRoute: typeof ClientInstituteBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/institution-auth': {
      id: '/client/institution-auth'
      path: '/client/institution-auth'
      fullPath: '/client/institution-auth'
      preLoaderRoute: typeof ClientInstitutionAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/launch-targets': {
      id: '/client/launch-targets'
      path: '/client/launch-targets'
      fullPath: '/client/launch-targets'
      preLoaderRoute: typeof ClientLaunchTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/ld-training': {
      id: '/client/ld-training'
      path: '/client/ld-training'
      fullPath: '/client/ld-training'
      preLoaderRoute: typeof ClientLdTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/notifications': {
      id: '/client/notifications'
      path: '/client/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof ClientNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/onboarding': {
      id: '/client/onboarding'
      path: '/client/onboarding'
      fullPath: '/client/onboarding'
      preLoaderRoute: typeof ClientOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/placement-cell': {
      id: '/client/placement-cell'
      path: '/client/placement-cell'
      fullPath: '/client/placement-cell'
      preLoaderRoute: typeof ClientPlacementCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/client/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/reports': {
      id: '/client/reports'
      path: '/client/reports'
      fullPath: '/client/reports'
      preLoaderRoute: typeof ClientReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/students': {
      id: '/client/students'
      path: '/client/students'
      fullPath: '/client/students'
      preLoaderRoute: typeof ClientStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication-training-report/$sessionId': {
      id: '/communication-training-report/$sessionId'
      path: '/communication-training-report/$sessionId'
      fullPath: '/communication-training-report/$sessionId'
      preLoaderRoute: typeof CommunicationTrainingReportSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-drives_/$companyId': {
      id: '/company-drives_/$companyId'
      path: '/company-drives/$companyId'
      fullPath: '/company-drives/$companyId'
      preLoaderRoute: typeof CompanyDrivesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-training-report/$sessionId': {
      id: '/english-training-report/$sessionId'
      path: '/english-training-report/$sessionId'
      fullPath: '/english-training-report/$sessionId'
      preLoaderRoute: typeof EnglishTrainingReportSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gd-report/$gdId': {
      id: '/gd-report/$gdId'
      path: '/gd-report/$gdId'
      fullPath: '/gd-report/$gdId'
      preLoaderRoute: typeof GdReportGdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-analysis/$interviewId': {
      id: '/interview-analysis/$interviewId'
      path: '/interview-analysis/$interviewId'
      fullPath: '/interview-analysis/$interviewId'
      preLoaderRoute: typeof InterviewAnalysisInterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-interview-transcript/$interviewId': {
      id: '/mock-interview-transcript/$interviewId'
      path: '/mock-interview-transcript/$interviewId'
      fullPath: '/mock-interview-transcript/$interviewId'
      preLoaderRoute: typeof MockInterviewTranscriptInterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-activity/$studentId': {
      id: '/student-activity/$studentId'
      path: '/student-activity/$studentId'
      fullPath: '/student-activity/$studentId'
      preLoaderRoute: typeof StudentActivityStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-data/$studentId': {
      id: '/student-data/$studentId'
      path: '/student-data/$studentId'
      fullPath: '/student-data/$studentId'
      preLoaderRoute: typeof StudentDataStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-detail/$studentId': {
      id: '/student-detail/$studentId'
      path: '/student-detail/$studentId'
      fullPath: '/student-detail/$studentId'
      preLoaderRoute: typeof StudentDetailStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-interview-evidence/$studentId/$interviewId': {
      id: '/student-interview-evidence/$studentId/$interviewId'
      path: '/student-interview-evidence/$studentId/$interviewId'
      fullPath: '/student-interview-evidence/$studentId/$interviewId'
      preLoaderRoute: typeof StudentInterviewEvidenceStudentIdInterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-module/$studentId/$moduleKey': {
      id: '/student-module/$studentId/$moduleKey'
      path: '/student-module/$studentId/$moduleKey'
      fullPath: '/student-module/$studentId/$moduleKey'
      preLoaderRoute: typeof StudentModuleStudentIdModuleKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CandidateRouteRouteChildren {
  CandidateAplrTrainingRoute: typeof CandidateAplrTrainingRoute
  CandidateAuthRoute: typeof CandidateAuthRoute
  CandidateBasicMathTrainingRoute: typeof CandidateBasicMathTrainingRoute
  CandidateChatRoute: typeof CandidateChatRoute
  CandidateCommunicationTrainingRoute: typeof CandidateCommunicationTrainingRoute
  CandidateCommunicationTrainingHistoryRoute: typeof CandidateCommunicationTrainingHistoryRoute
  CandidateCommunicationTrainingTipsRoute: typeof CandidateCommunicationTrainingTipsRoute
  CandidateCoursesRoute: typeof CandidateCoursesRoute
  CandidateDailyTargetsRoute: typeof CandidateDailyTargetsRoute
  CandidateDiscussionForumRoute: typeof CandidateDiscussionForumRoute
  CandidateDsaTrainingRoute: typeof CandidateDsaTrainingRoute
  CandidateEnglishTrainingRoute: typeof CandidateEnglishTrainingRoute
  CandidateEnglishTrainingHistoryRoute: typeof CandidateEnglishTrainingHistoryRoute
  CandidateEnglishTrainingTipsRoute: typeof CandidateEnglishTrainingTipsRoute
  CandidateGdHistoryRoute: typeof CandidateGdHistoryRoute
  CandidateGdRoomRoute: typeof CandidateGdRoomRoute
  CandidateGdTrainingRoute: typeof CandidateGdTrainingRoute
  CandidateLeaderboardRoute: typeof CandidateLeaderboardRoute
  CandidateLearningRoute: typeof CandidateLearningRoute
  CandidateMockInterviewRoute: typeof CandidateMockInterviewRoute
  CandidateMockInterviewHistoryRoute: typeof CandidateMockInterviewHistoryRoute
  CandidateNotificationsRoute: typeof CandidateNotificationsRoute
  CandidateOnboardingRoute: typeof CandidateOnboardingRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateResumeBuilderRoute: typeof CandidateResumeBuilderRoute
  CandidateRoadmapDrillRoute: typeof CandidateRoadmapDrillRoute
  CandidateSelfTrainingRoute: typeof CandidateSelfTrainingRoute
  CandidateSituationalTrainingRoute: typeof CandidateSituationalTrainingRoute
  CandidateStudentMessageRoute: typeof CandidateStudentMessageRoute
  CandidateTechnicalTrainingRoute: typeof CandidateTechnicalTrainingRoute
  CandidateTutorialsRoute: typeof CandidateTutorialsRoute
}

const CandidateRouteRouteChildren: CandidateRouteRouteChildren = {
  CandidateAplrTrainingRoute: CandidateAplrTrainingRoute,
  CandidateAuthRoute: CandidateAuthRoute,
  CandidateBasicMathTrainingRoute: CandidateBasicMathTrainingRoute,
  CandidateChatRoute: CandidateChatRoute,
  CandidateCommunicationTrainingRoute: CandidateCommunicationTrainingRoute,
  CandidateCommunicationTrainingHistoryRoute:
    CandidateCommunicationTrainingHistoryRoute,
  CandidateCommunicationTrainingTipsRoute:
    CandidateCommunicationTrainingTipsRoute,
  CandidateCoursesRoute: CandidateCoursesRoute,
  CandidateDailyTargetsRoute: CandidateDailyTargetsRoute,
  CandidateDiscussionForumRoute: CandidateDiscussionForumRoute,
  CandidateDsaTrainingRoute: CandidateDsaTrainingRoute,
  CandidateEnglishTrainingRoute: CandidateEnglishTrainingRoute,
  CandidateEnglishTrainingHistoryRoute: CandidateEnglishTrainingHistoryRoute,
  CandidateEnglishTrainingTipsRoute: CandidateEnglishTrainingTipsRoute,
  CandidateGdHistoryRoute: CandidateGdHistoryRoute,
  CandidateGdRoomRoute: CandidateGdRoomRoute,
  CandidateGdTrainingRoute: CandidateGdTrainingRoute,
  CandidateLeaderboardRoute: CandidateLeaderboardRoute,
  CandidateLearningRoute: CandidateLearningRoute,
  CandidateMockInterviewRoute: CandidateMockInterviewRoute,
  CandidateMockInterviewHistoryRoute: CandidateMockInterviewHistoryRoute,
  CandidateNotificationsRoute: CandidateNotificationsRoute,
  CandidateOnboardingRoute: CandidateOnboardingRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateResumeBuilderRoute: CandidateResumeBuilderRoute,
  CandidateRoadmapDrillRoute: CandidateRoadmapDrillRoute,
  CandidateSelfTrainingRoute: CandidateSelfTrainingRoute,
  CandidateSituationalTrainingRoute: CandidateSituationalTrainingRoute,
  CandidateStudentMessageRoute: CandidateStudentMessageRoute,
  CandidateTechnicalTrainingRoute: CandidateTechnicalTrainingRoute,
  CandidateTutorialsRoute: CandidateTutorialsRoute,
}

const CandidateRouteRouteWithChildren = CandidateRouteRoute._addFileChildren(
  CandidateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidateRouteRoute: CandidateRouteRouteWithChildren,
  DowntimeRoute: DowntimeRoute,
  GetStartedRoute: GetStartedRoute,
  LogoutRoute: LogoutRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SandboxRoute: SandboxRoute,
  TacRoute: TacRoute,
  ClientAuthRoute: ClientAuthRoute,
  ClientChatRoute: ClientChatRoute,
  ClientClientChatRoute: ClientClientChatRoute,
  ClientClientOnboardingRoute: ClientClientOnboardingRoute,
  ClientClientProfileRoute: ClientClientProfileRoute,
  ClientCompaniesRoute: ClientCompaniesRoute,
  ClientCompanyDrivesRoute: ClientCompanyDrivesRoute,
  ClientDrivesRoute: ClientDrivesRoute,
  ClientInstituteBillingRoute: ClientInstituteBillingRoute,
  ClientInstitutionAuthRoute: ClientInstitutionAuthRoute,
  ClientLaunchTargetsRoute: ClientLaunchTargetsRoute,
  ClientLdTrainingRoute: ClientLdTrainingRoute,
  ClientNotificationsRoute: ClientNotificationsRoute,
  ClientOnboardingRoute: ClientOnboardingRoute,
  ClientPlacementCellRoute: ClientPlacementCellRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientReportsRoute: ClientReportsRoute,
  ClientStudentsRoute: ClientStudentsRoute,
  CommunicationTrainingReportSessionIdRoute:
    CommunicationTrainingReportSessionIdRoute,
  CompanyDrivesCompanyIdRoute: CompanyDrivesCompanyIdRoute,
  EnglishTrainingReportSessionIdRoute: EnglishTrainingReportSessionIdRoute,
  GdReportGdIdRoute: GdReportGdIdRoute,
  InterviewAnalysisInterviewIdRoute: InterviewAnalysisInterviewIdRoute,
  MockInterviewTranscriptInterviewIdRoute:
    MockInterviewTranscriptInterviewIdRoute,
  StudentActivityStudentIdRoute: StudentActivityStudentIdRoute,
  StudentDataStudentIdRoute: StudentDataStudentIdRoute,
  StudentDetailStudentIdRoute: StudentDetailStudentIdRoute,
  StudentInterviewEvidenceStudentIdInterviewIdRoute:
    StudentInterviewEvidenceStudentIdInterviewIdRoute,
  StudentModuleStudentIdModuleKeyRoute: StudentModuleStudentIdModuleKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
